import React, { useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import { HashRouter, NavLink, Route, Routes, useNavigate } from "react-router-dom";
import {
  AlertCircle, Archive, BarChart3, Bell, Building2, Calculator, Check, CheckCircle2,
  ChevronRight, ClipboardCheck, Database, Download, FileClock, FileSpreadsheet,
  Flag, LayoutDashboard, ListChecks, Menu, Plus, RefreshCw, Search, Settings,
  ShieldCheck, SlidersHorizontal, Target, Upload, Users, X
} from "lucide-react";
import "./styles.css";

type Role = "經營企劃部管理者" | "評分部門主管" | "評分部門承辦人" | "分行查詢者" | "系統管理員" | "稽核唯讀查詢者";
type Status = "草稿" | "部門主管審核中" | "經營企劃部審核中" | "已生效" | "退回修改" | "停用";
type Indicator = { code:string; name:string; group:string; dept:string; base:number; bonus:number; penalty:number; modules:number; status:Status; owner:string; updated:string };

const roles:Role[]=["經營企劃部管理者","評分部門主管","評分部門承辦人","分行查詢者","系統管理員","稽核唯讀查詢者"];
const departments=["經營企劃部","財務會計部","風險管理部","企金行銷部","個金行銷部","財富管理部","信託部","保險代理人部","數位經營部","營運管理部","國際金融部","債權管理部","授信管理部","法令遵循部","董事會稽核部","人力資源部","資訊安全部","資訊作業服務部","資訊規劃開發部","通路暨作業管理部","金融市場管理部","徵信產經研究部","客戶服務部","金融交易部","數位金融部","其他管理部門"];
const branchNames=["台北分行","松江分行","板橋分行","新店分行","桃園分行","新竹分行","台中分行","彰化分行","嘉義分行","台南分行","高雄分行","鳳山分行",...Array.from({length:20},(_,i)=>`示範分行 ${String(i+13).padStart(2,"0")}`)];
const initialIndicators:Indicator[]=[
 {code:"KPI-FEE-01",name:"手續費收益成長率",group:"收益成長",dept:"財務會計部",base:8,bonus:2,penalty:2,modules:2,status:"已生效",owner:"陳怡君",updated:"115/05/22 09:18"},
 {code:"KPI-DEP-02",name:"新臺幣存款",group:"存款業務",dept:"個金行銷部",base:12,bonus:3,penalty:0,modules:3,status:"經營企劃部審核中",owner:"林俊宏",updated:"115/05/22 08:40"},
 {code:"KPI-SME-03",name:"移送信保業務",group:"企金業務",dept:"企金行銷部",base:10,bonus:2,penalty:1,modules:4,status:"部門主管審核中",owner:"吳佳蓉",updated:"115/05/21 16:25"},
 ...Array.from({length:15},(_,i)=>({code:`KPI-${String(i+4).padStart(3,"0")}`,name:["數位帳戶活躍率","房貸新增餘額","財富管理 AUM 增量","信用卡有效卡數成長率","企業授信餘額"][i%5],group:["數位金融","放款業務","財富管理"][i%3],dept:departments[(i+3)%departments.length],base:5+i%6,bonus:i%3,penalty:i%2,modules:1+i%4,status:["草稿","已生效","退回修改","已生效"][i%4] as Status,owner:["王小明","李佩珊","張志豪"][i%3],updated:`115/05/${String(20-i%8).padStart(2,"0")} 14:20`}))
];
const nav=[
 ["/","作業總覽",LayoutDashboard],["/indicators","年度指標管理",Target],["/branches","分行與分組",Users],["/targets","分行目標",Flag],["/upload","月度業績上傳",Upload],["/scoring","試算與計分",Calculator],["/approval","審核與發布",ShieldCheck],["/reports","報表與排名",BarChart3],["/appeals","申覆管理",ClipboardCheck],["/tasks","通知與待辦",Bell],["/settings","系統設定",Settings],["/logs","操作與計算紀錄",FileClock]
] as const;

function App(){
 const [role,setRole]=useState<Role>("評分部門承辦人"); const [collapsed,setCollapsed]=useState(false);
 const visibleNav=role==="分行查詢者"?nav.filter((x)=>["/","/reports","/appeals","/tasks"].includes(x[0])):role==="稽核唯讀查詢者"?nav.filter(x=>["/","/reports","/logs"].includes(x[0])):nav;
 return <div className="app"><aside className={collapsed?"side collapsed":"side"}><div className="brand"><Building2/><div><b>分行績效管理系統</b><small>BRANCH PERFORMANCE</small></div></div><nav>{visibleNav.map(([p,l,I])=><NavLink key={p} to={p} end={p==="/"}><I/><span>{l}</span></NavLink>)}</nav><div className="side-foot"><ShieldCheck/><span>115年度績效作業</span></div></aside>
 <main className={collapsed?"main collapsed":"main"}><header><button className="icon" onClick={()=>setCollapsed(!collapsed)}><Menu/></button><div className="header-tools"><select><option>115 年度</option><option>114 年度</option></select><select><option>5 月</option><option>4 月</option></select><button className="notify"><Bell/><i>12</i></button><span className="avatar">王</span><select value={role} onChange={e=>setRole(e.target.value as Role)}>{roles.map(r=><option key={r}>{r}</option>)}</select></div></header>
 <Routes><Route path="/" element={<Dashboard role={role}/>}/><Route path="/indicators" element={<Indicators/>}/><Route path="/branches" element={<Branches/>}/><Route path="/targets" element={<Targets/>}/><Route path="/upload" element={<UploadPage/>}/><Route path="/scoring" element={<Scoring/>}/><Route path="/approval" element={<Approval/>}/><Route path="/reports" element={<Reports role={role}/>}/><Route path="/appeals" element={<Appeals/>}/><Route path="/tasks" element={<Tasks/>}/><Route path="/settings" element={<SettingsPage/>}/><Route path="/logs" element={<Logs/>}/></Routes></main></div>
}
function Page({title,sub,actions,children}:{title:string;sub?:string;actions?:React.ReactNode;children:React.ReactNode}){return <div className="page"><div className="crumb">首頁 <ChevronRight/> {title}</div><div className="titlebar"><div><h1>{title}</h1>{sub&&<p>{sub}</p>}</div><div className="actions">{actions}</div></div>{children}</div>}
function Badge({children,tone="blue"}:{children:React.ReactNode;tone?:string}){return <span className={`badge ${tone}`}>{children}</span>}
function Dashboard({role}:{role:Role}){
 if(role==="分行查詢者") return <BranchDashboard/>;
 const dept=role.includes("評分部門");
 return <Page title={dept?"本部門工作桌面":"作業總覽"} sub={dept?"企金行銷部｜115年5月":"掌握 26 個評分部門本月上傳、審核、計分與發布進度"} actions={<><button><RefreshCw/>更新</button><button><Download/>匯出進度</button></>}>
 <div className="workflow">{(dept?[["本部門指標","13"],["待上傳","3"],["主管審核","2"],["已正式計分","8"],["已發布","7"]]:[["指標設定","128"],["業績上傳","23 / 26"],["審核中","18"],["正式計分","64"],["已發布","51"]]).map((x,i)=><React.Fragment key={x[0]}><div className={`stage s${i+1}`}><i>{i+1}</i><span>{x[0]}</span><b>{x[1]}</b><small>{i===2?"3 件逾期":i===4?"完成率 79.7%":"115年5月"}</small></div>{i<4&&<ChevronRight className="stage-arrow"/>}</React.Fragment>)}</div>
 <div className="dash-grid"><section className="panel progress-panel"><div className="panel-head"><div><h2>{dept?"本部門負責指標":"26 個總行評分部門本月進度"}</h2><p>{dept?"企金行銷部負責指標，適用全部分行":"經營企劃部彙總各總行評分部門作業狀態"}｜更新時間：115/05/22 10:30</p></div><div className="legend"><i className="green"/>完成 <i className="amber"/>進行中 <i className="gray"/>未開始</div></div><DepartmentTable short={dept}/></section><aside><TaskPanel/><NoticePanel/></aside></div>{dept?<BranchProgress/>:<Recent/>}</Page>
}
function DepartmentTable({short=false}:{short?:boolean}){const rows=(short?initialIndicators.slice(0,7):departments.slice(0,12));return <div className="table-scroll"><table><thead><tr><th>{short?"指標":"部門"}</th><th>指標數</th><th>上傳</th><th>主管審核</th><th>經企確認</th><th>正式計分</th><th>發布</th><th>狀態</th></tr></thead><tbody>{rows.map((r:any,i)=>{const name=short?r.name:r;const total=short?1:8+i%7;const progress=Math.max(0,total-Math.floor(i/2));return <tr key={name}><td><b>{name}</b>{short&&<small>{r.code}</small>}</td><td>{total}</td><td>{progress}</td><td>{Math.max(0,progress-(i%3===2?1:0))}</td><td>{Math.max(0,progress-Math.floor(i/4))}</td><td>{Math.max(0,progress-Math.floor(i/3))}</td><td>{Math.max(0,progress-Math.floor(i/2))}</td><td><Badge tone={i<3?"green":i<8?"amber":"gray"}>{i<3?"已發布":i<8?"進行中":"未上傳"}</Badge><span className="mini-progress"><i style={{width:`${Math.max(8,100-i*8)}%`}}/></span></td></tr>})}</tbody></table></div>}
function TaskPanel(){return <section className="panel"><div className="panel-head"><h2>我的待辦</h2><a>全部 12 件</a></div><div className="tasks">{[["主管審核","移送信保業務規則審核","今天","red"],["經企確認","新臺幣存款 5月業績","今天","red"],["業績上傳","手續費收益成長率","明天","amber"],["申覆案件","台中分行 4月申覆","05/24","blue"]].map(x=><div><Badge tone={x[3]}>{x[0]}</Badge><span>{x[1]}</span><b>{x[2]}</b></div>)}</div></section>}
function NoticePanel(){return <section className="panel"><div className="panel-head"><h2>系統通知</h2><a>更多</a></div><ul className="notices"><li><AlertCircle/>5月上傳截止日為 05/24 18:00</li><li><CheckCircle2/>企金行銷部 3 項指標已完成確認</li><li><Bell/>系統維護：05/25 22:00–24:00</li></ul></section>}
function Recent(){return <section className="panel recent"><div className="panel-head"><h2>近期操作紀錄</h2><a>查看更多</a></div><table><thead><tr><th>時間</th><th>操作人員</th><th>角色</th><th>操作模組</th><th>操作內容</th><th>結果</th></tr></thead><tbody>{[["10:25","王小明","經企人員","審核與發布","確認松江分行 5 月業績"],["10:20","王小明","經企人員","試算與計分","執行新臺幣存款試算"],["10:05","李主任","部門主管","審核與發布","核准移送信保業務"]].map(r=><tr>{r.map(x=><td>{x}</td>)}<td><Badge tone="green">成功</Badge></td></tr>)}</tbody></table></section>}
function BranchProgress(){return <section className="panel recent"><div className="panel-head"><div><h2>各分行計分進度</h2><p>企金行銷部依本部門指標考核各分行</p></div><a>查看全部 32 家</a></div><table><thead><tr><th>分行代碼</th><th>分行</th><th>分組</th><th>已完成指標</th><th>待補資料</th><th>試算分數</th><th>正式分數</th><th>發布狀態</th></tr></thead><tbody>{branchNames.slice(0,8).map((x,i)=><tr><td>{101+i}</td><td><b>{x}</b></td><td>第 {i%8+1} 組</td><td>{9-i%3} / 13</td><td>{i%4===0?1:0}</td><td>{(78+i*1.26).toFixed(2)}</td><td>{i<5?(77.6+i*1.18).toFixed(2):"—"}</td><td><Badge tone={i<4?"green":i<6?"amber":"gray"}>{i<4?"部分發布":i<6?"待審核":"未完成"}</Badge></td></tr>)}</tbody></table></section>}
function BranchDashboard(){return <Page title="台北分行績效總覽" sub="115年度 5月｜已發布部分得分，目前完整月份尚未完成。"><div className="summary-grid">{[["本月已發布得分","82.60"],["年度累計得分","398.45"],["同組排名","3 / 18"],["已發布指標","51 / 64"]].map(x=><div className="summary"><span>{x[0]}</span><b>{x[1]}</b></div>)}</div><section className="panel"><div className="panel-head"><h2>最近發布結果</h2><button><Download/>匯出得分表</button></div><DepartmentTable short/></section></Page>}

function Indicators(){const [items,setItems]=useState(initialIndicators);const [q,setQ]=useState("");const [wizard,setWizard]=useState(false);const rows=items.filter(x=>(x.name+x.code+x.dept).includes(q));return <Page title="年度指標管理" sub="建立、審核與維護年度績效指標及計分規則" actions={<><button>複製到新年度</button><button className="primary" onClick={()=>setWizard(true)}><Plus/>新增指標</button></>}><div className="filterbar"><select><option>115年度</option></select><select><option>全部部門</option>{departments.map(x=><option>{x}</option>)}</select><select><option>全部狀態</option><option>草稿</option><option>已生效</option></select><div className="search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="搜尋指標代碼或名稱"/></div></div><div className="table-box"><table><thead><tr><th>年度／指標</th><th>名稱／群組</th><th>主責部門</th><th>基本配分</th><th>加分上限</th><th>扣分上限</th><th>模組</th><th>狀態</th><th>更新人／時間</th><th>操作</th></tr></thead><tbody>{rows.slice(0,12).map(x=><tr><td><b>115｜{x.code}</b></td><td><b>{x.name}</b><small>{x.group}</small></td><td>{x.dept}</td><td>{x.base.toFixed(2)}</td><td>+{x.bonus.toFixed(2)}</td><td>-{x.penalty.toFixed(2)}</td><td>{x.modules}</td><td><Badge tone={x.status==="已生效"?"green":x.status==="退回修改"?"red":"amber"}>{x.status}</Badge></td><td>{x.owner}<small>{x.updated}</small></td><td><button className="link" onClick={()=>setWizard(true)}>編輯</button></td></tr>)}</tbody></table></div>{wizard&&<IndicatorWizard onClose={()=>setWizard(false)} onSave={x=>{setItems([x,...items]);setWizard(false)}}/>}</Page>}
function IndicatorWizard({onClose,onSave}:{onClose:()=>void;onSave:(x:Indicator)=>void}){const [step,setStep]=useState(1);const [name,setName]=useState("企業授信成長率");const labels=["基本資料","輸入欄位","計分模組","配分與上下限","預覽"];return <div className="overlay"><div className="drawer wide"><div className="drawer-head"><div><span>新增年度指標</span><h2>{labels[step-1]}</h2></div><button className="icon" onClick={onClose}><X/></button></div><div className="steps">{labels.map((x,i)=><div className={i+1<=step?"active":""}><i>{i+1<step?<Check/>:i+1}</i><span>{x}</span></div>)}</div><div className="drawer-body">{step===1&&<div className="form-grid"><Field label="年度"><select><option>115年度</option></select></Field><Field label="指標代碼"><input defaultValue="KPI-CORP-019"/></Field><Field label="指標名稱"><input value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="指標簡稱"><input defaultValue="企授成長"/></Field><Field label="所屬群組"><select><option>企金業務</option></select></Field><Field label="主責部門"><select><option>企金行銷部</option></select></Field><Field label="基本配分"><input type="number" defaultValue="10"/></Field><Field label="計分週期"><select><option>每月</option></select></Field></div>}{step===2&&<EditableRows title="輸入欄位" rows={["本期授信餘額｜金額｜萬元｜必填","去年同期授信餘額｜金額｜萬元｜必填","成長率｜百分比｜%｜系統計算"]}/>} {step===3&&<EditableRows title="計分模組" rows={["目標達成率級距｜配分 6.00","成長率級距｜配分 4.00","超額達成加分｜上限 2.00"]}/>} {step===4&&<div><div className="validation ok"><CheckCircle2/>配分檢核通過：基本配分 10.00，加分上限 2.00，扣分上限 1.00</div><div className="form-grid"><Field label="基本配分"><input value="10.00" readOnly/></Field><Field label="加分上限"><input value="2.00" readOnly/></Field><Field label="扣分上限"><input value="1.00" readOnly/></Field><Field label="總分上限"><input value="12.00" readOnly/></Field></div></div>}{step===5&&<div className="preview"><h3>{name}</h3><p>KPI-CORP-019｜企金行銷部｜每月計分</p><div className="rule-flow"><span>輸入本期值</span><ChevronRight/><span>達成率級距</span><ChevronRight/><span>成長率級距</span><ChevronRight/><span>套用上下限</span><ChevronRight/><b>最終得分 8.60</b></div><div className="validation ok"><CheckCircle2/>模擬試算完成，所有規則與配分檢核均通過。</div></div>}</div><div className="drawer-actions"><button onClick={onClose}>取消</button>{step>1&&<button onClick={()=>setStep(step-1)}>上一步</button>}<button className="primary" onClick={()=>step<5?setStep(step+1):onSave({code:"KPI-CORP-019",name,group:"企金業務",dept:"企金行銷部",base:10,bonus:2,penalty:1,modules:3,status:"草稿",owner:"王小明",updated:"剛剛"})}>{step<5?"下一步":"建立草稿"}</button></div></div></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="field"><span>{label}</span>{children}</label>}
function EditableRows({title,rows}:{title:string;rows:string[]}){return <div><div className="section-title"><h3>{title}</h3><button><Plus/>新增</button></div><div className="edit-list">{rows.map((x,i)=><div><b>{i+1}</b><span>{x}</span><button className="link">設定</button></div>)}</div></div>}

function Branches(){return <SimpleTable title="分行與分組管理" sub="由經營企劃部維護 8 個年度分組與 32 家示範分行" columns={["分行代碼","分行名稱","年度分組","啟用狀態","生效年度","操作"]} rows={branchNames.slice(0,15).map((x,i)=>[String(101+i),x,`第 ${(i%8)+1} 組`,"啟用","115年度","編輯"])}/>}
function Targets(){return <SimpleTable title="分行目標管理" sub="設定年度及月度目標，可使用 Excel 批次匯入" columns={["分行","指標","年度目標","5月目標","完成率","更新時間"]} rows={branchNames.slice(0,12).map((x,i)=>[x,"新臺幣存款",`${1200+i*45} 百萬元`,`${100+i*3} 百萬元`,`${82+i%12}%`,`115/05/${20+i%3}`])} actions={<><button><Download/>下載範本</button><button className="primary"><Upload/>批次上傳</button></>}/>}
function UploadPage(){const [file,setFile]=useState("");const [stage,setStage]=useState<"pick"|"check"|"ok">("pick");return <Page title="月度業績上傳" sub="下載指標專屬範本、上傳並執行全檔檢核"><div className="upload-layout"><section className="panel"><div className="form-grid"><Field label="年度"><select><option>115年度</option></select></Field><Field label="月份"><select><option>5月</option></select></Field><Field label="主責指標"><select><option>新臺幣存款｜KPI-DEP-02</option></select></Field><Field label="範本"><button><Download/>下載專屬 Excel 範本</button></Field></div><label className="dropzone"><Upload/><h2>{file||"拖曳或選擇業績 Excel"}</h2><p>支援 .xlsx；只要一筆錯誤，整份檔案不匯入</p><input type="file" accept=".xlsx" onChange={e=>{setFile(e.target.files?.[0]?.name||"11505_新臺幣存款.xlsx");setStage("check")}}/></label>{stage!=="pick"&&<div className="file-row"><FileSpreadsheet/><div><b>{file}</b><small>32 筆分行資料｜9 個欄位</small></div><button className="primary" onClick={()=>setStage("ok")}><ListChecks/>執行檢核</button></div>}</section><section className="panel check-panel"><h2>上傳檢核</h2>{stage==="pick"?<div className="empty"><Database/><p>尚未選擇檔案</p></div>:stage==="check"?<div className="empty"><RefreshCw/><p>檔案已讀取，請執行檢核</p></div>:<><div className="validation ok"><CheckCircle2/>檢核成功：32 筆資料均可匯入</div>{["分行代碼","指標代碼","年度月份","必填欄位","數值與百分比格式","重複與缺漏資料"].map(x=><div className="check"><Check/> {x}<b>通過</b></div>)}<button className="primary full">匯入並產生試算</button></>}</section></div></Page>}
function Scoring(){const [run,setRun]=useState(false);return <Page title="試算與正式計分" sub="檢視模組計算明細、分組排名與上下限調整" actions={<button className="primary" onClick={()=>setRun(true)}><Calculator/>{run?"重新試算":"執行試算"}</button>}><div className="score-head"><Badge tone={run?"green":"amber"}>{run?"試算完成":"待試算"}</Badge><b>新臺幣存款｜115年5月</b><span>32 家分行｜最後執行：{run?"剛剛":"尚未執行"}</span></div><div className="table-box"><table><thead><tr><th>分行</th><th>實際值</th><th>目標值</th><th>達成率</th><th>分組</th><th>排名</th><th>中位數差補</th><th>超額加分</th><th>調整前</th><th>最終得分</th><th>明細</th></tr></thead><tbody>{branchNames.slice(0,14).map((x,i)=>{let rate=82+i*1.9;let score=run?Math.min(12,6+(rate-80)*.18):0;return <tr><td><b>{x}</b></td><td>{(980+i*26).toLocaleString()}</td><td>{(1050+i*18).toLocaleString()}</td><td>{rate.toFixed(2)}%</td><td>第 {i%8+1} 組</td><td>{i%6+1}</td><td>{run?(score-.4).toFixed(2):"—"}</td><td>{run?Math.max(0,(rate-100)*.1).toFixed(2):"—"}</td><td>{run?(score+.2).toFixed(2):"—"}</td><td><b>{run?score.toFixed(2):"—"}</b></td><td><button className="link">查看</button></td></tr>})}</tbody></table></div></Page>}
function Approval(){const [done,setDone]=useState<string[]>([]);const items=["移送信保業務｜主管審核","新臺幣存款｜經企確認","手續費收益成長率｜正式計分","數位帳戶活躍率｜待發布"];return <Page title="審核與發布" sub="依序完成部門主管審核、經企確認、正式計分與部門發布"><div className="approval-board">{["待部門主管審核","待經企確認","待正式計分","待發布"].map((h,i)=><section><div className="approval-title"><h2>{h}</h2><Badge>{done.includes(items[i])?0:3+i}</Badge></div><div className="approval-card"><small>KPI-00{i+1}｜115年5月</small><b>{items[i].split("｜")[0]}</b><p>企金行銷部 · 王小明</p>{done.includes(items[i])?<Badge tone="green">已完成</Badge>:<button className="primary" onClick={()=>setDone([...done,items[i]])}>{i===3?"發布":"檢視並核准"}</button>}</div></section>)}</div></Page>}
function Reports({role}:{role:Role}){return <SimpleTable title="報表與排名" sub={role==="分行查詢者"?"台北分行已發布得分與同組排名":"查詢並匯出全行績效報表"} columns={["排名","分行","分組","5月得分","年度累計","已發布指標","狀態"]} rows={branchNames.slice(0,15).map((x,i)=>[String(i+1),x,`第 ${i%8+1} 組`,(92-i*.7).toFixed(2),(420-i*4.2).toFixed(2),`${51-i%4} / 64`,i<4?"領先":"正常"])} actions={<button><Download/>匯出 Excel</button>}/>}
function Appeals(){const [open,setOpen]=useState(false);return <SimpleTable title="申覆管理" sub="追蹤分行提出的單一指標申覆與處理結果" columns={["案件編號","月份","分行","指標","目前得分","提出時間","處理狀態","操作"]} rows={[["APL-11505001","115/05","台中分行","新臺幣存款","8.40","115/05/22","評分部門處理中","處理"],["APL-11504007","115/04","板橋分行","手續費收益成長率","6.20","115/05/18","已完成","查看"]]} actions={<button className="primary" onClick={()=>setOpen(!open)}><Plus/>提出申覆</button>}/>}
function Tasks(){return <SimpleTable title="通知與待辦" sub="站內通知、期限提醒與 Email 模擬寄送紀錄" columns={["通知類型","內容","對象","寄送方式","狀態","時間"]} rows={[["逾期催辦","5月業績尚未上傳","數位經營部","站內＋Email","已寄送","10:30"],["指標退回","新臺幣存款需修正配分","個金行銷部","站內","未讀","09:18"],["審核完成","移送信保業務已生效","企金行銷部","站內＋Email","已讀","昨天"]]}/>}
function SettingsPage(){return <Page title="系統設定" sub="年度參數、部門配分、期限與通知規則"><div className="settings-grid">{["績效年度設定","26 部門與權限","全行配分上限","月度作業期限","通知與催辦規則","計分模組目錄"].map((x,i)=><section className="setting-card"><div><Settings/><h2>{x}</h2></div><p>{i===0?"目前年度：115年度":i===1?"26 個部門／6 種角色":"點選進入維護設定"}</p><button>管理設定 <ChevronRight/></button></section>)}</div></Page>}
function Logs(){return <SimpleTable title="操作與計算紀錄" sub="完整保留異動前後內容、計算參數、中間結果與最終結果" columns={["時間","執行人","角色","模組","動作","對象","追蹤編號","結果"]} rows={Array.from({length:12},(_,i)=>[`115/05/22 10:${25-i}`,i%2?"王小明":"李佩珊",i%2?"經企人員":"部門主管",i%3?"試算與計分":"年度指標","執行試算",branchNames[i],`TRC-1150522${i}`,"成功"])}/>}
function SimpleTable({title,sub,columns,rows,actions}:{title:string;sub:string;columns:string[];rows:string[][];actions?:React.ReactNode}){return <Page title={title} sub={sub} actions={actions||<button className="primary"><Plus/>新增</button>}><div className="filterbar"><select><option>115年度</option></select><select><option>5月</option></select><div className="search"><Search/><input placeholder="搜尋關鍵字"/></div></div><div className="table-box"><table><thead><tr>{columns.map(x=><th>{x}</th>)}</tr></thead><tbody>{rows.map(r=><tr>{r.map((x,i)=><td>{i===0?<b>{x}</b>:i===r.length-1?<Badge tone={x.includes("完成")||x.includes("成功")||x==="啟用"?"green":"blue"}>{x}</Badge>:x}</td>)}</tr>)}</tbody></table></div></Page>}

createRoot(document.getElementById("root")!).render(<HashRouter><App/></HashRouter>);
